name: BuildAndRelease
on: push


jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: platformio run -e esp32doit-devkit-v1 -e esp32doit-devkit-v1-nocertcheck
      - name: Rename release files
        run: mv .pio/build/esp32doit-devkit-v1-nocertcheck/firmware.bin .pio/build/esp32doit-devkit-v1-nocertcheck/firmware-nocertcheck.bin
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .pio/build/esp32doit-devkit-v1/firmware.bin
            .pio/build/esp32doit-devkit-v1-nocertcheck/firmware-nocertcheck.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
